name: Deploy to AWS Lambda

on:
  push:
    branches:
      - test 
    paths:
      - 'lambda_handler.py'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install boto3 awscli zappa

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Deploy lambda_handler.py to Lambda
      run:
        zappa update production  